
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-HomeController","number":30,"title":"Update HomeController.java","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-UniversityQueryService-Controller","number":29,"title":"Add UniversityQuery Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/29"},{"author":{"id":"MDQ6VXNlcjIyODI3MjU0","is_bot":false,"login":"SloggyYoggy","name":"Sloggy Yoggy"},"headRefName":"Aaron-ZipcodeService","number":28,"title":"Aaron zipcode service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/28"},{"author":{"id":"U_kgDOBdHiDg","is_bot":false,"login":"NevMan1","name":""},"headRefName":"nevin-JokeQueryService","number":27,"title":"Nevin joke query service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/27"},{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"Richard-LocationController","number":26,"title":"Richard location controller and test written","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/26"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-UniversityQueryService","number":25,"title":"Add UniversityQuery Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/25"},{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"Richard-LocationQueryService","number":24,"title":"Richard- Added location query service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/24"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-PublicHolidayQueryService-Controller","number":23,"title":"Add Public Holiday Query Service Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/23"},{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-Tides","number":21,"title":"Add Tides Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/21"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-PublicHolidayQueryService","number":19,"title":"Add PublicHolidayQuery Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/19"}]
