
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBdC-cw","is_bot":false,"login":"nicoshinozaki","name":""},"headRefName":"Nico-Tides","number":21,"title":"Add Tides Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/21"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-PublicHolidayQueryService","number":19,"title":"Add PublicHolidayQuery Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/19"},{"author":{"id":"MDQ6VXNlcjUzNzQwNDY0","is_bot":false,"login":"ukyl","name":""},"headRefName":"ukyl-UniversityQueryService","number":18,"title":"readme added university query","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-2/pull/18"}]
